### ISSUE TITLE
response_format supported options

### ISSUE THREAD

**Issue by lucadelu** [pesekon2/GRASS-GIS-SOS-tools#4]
I propose to use `options` parameter (like [here](https://trac.osgeo.org/grass/browser/grass/trunk/scripts/v.rast.stats/v.rast.stats.py#L54) ) for `response_format` (used [here](https://github.com/pesekon2/GRASS-GIS-SOS-tools/blob/master/v.in.sos/v.in.sos.py#L43) ) to permit to use only the supported `responseFormat`

**Comment by pesekon2** [comment]
The only problem is that not every `responseFormat` is supported for both SOS versions (1.0.0. and 2.0.0.). For example the standardized `text/xml;subtype="om/1.0.0"` is supported only for version 1.0.0. Should I reflect it somehow, or should I write there all of them? 

I think that the best idea is to write there (into `options`) just those implemented in module, now `text/xml;subtype="om/1.0.0"` and `text/json`, because it doesn't make sense to choose `text/plain` when `text/xml;subtype="om/1.0.0"` should be provided in every SOS 1.0.0.

**Comment by lucadelu** [comment]
Yes please, add only the implemented in the module.

Maybe add a check if `responseFormat` is `text/xml;subtype="om/1.0.0"` and SOS version is `1.0.0`
