### ISSUE TITLE
Support more output formats for measurements

### ISSUE THREAD

**Issue by ninsbl** [pesekon2/GRASS-GIS-SOS-tools#41]
It would be useful to also be able to get data esp. in "text/plain" format, which is quite efficient and could be read directly into DB with e.g.:
https://stackoverflow.com/questions/2887878/importing-a-csv-file-into-a-sqlite3-database-table-using-python

Not sure how important: text/xml; text/x-json would be.

Non OGC-compliant output formats could be marked "vendor specific" in the manual. If the default is OGC compliant output format, no harm should be done...

**Comment by pesekon2** [comment]
Actually, I was even thinking about discarding the JSON option... 

The problem with those "vendor specific" formats is that they may (and do) look different when using different SOS servers. CSV from istSOS may contain other informations than the ones from MapServer or 52N. So there can be five different TXT formats in the end and cause just mess. 

I don't have any problem with implementing that, but I don't see high priority in that since the standardized format should be provided by all of them.

**Comment by ninsbl** [comment]
Good point! I see the problem.
Maybe naming the option "istsos;text/plain" or "52north;text/plain" could avoid such confusion and allow to add vendor specific output formats as needed.
I agree that the standard format is essential. And everything else is just additional (and thus less a priority).

**Comment by pesekon2** [comment]
After a discussion,  a consensus to to drop the JSON support has been reached. Only SOS will be supported.
