### ISSUE TITLE
more than one offering

### ISSUE THREAD

**Issue by lucadelu** [pesekon2/GRASS-GIS-SOS-tools#9]
Please add support for multiple offering, with the request

```
v.in.sos.py url=http://istsos.org/istsos/demo? offering=LOCARNO,BELLINZONA observed_properties='urn:ogc:def:parameter:x-istsos:1.0:meteo:air:temperature' response_format='text/xml;subtype="om/1.0.0"' output=istsos_demo_2procs event_time="2014-06-03T13:00:00+01:00/2014-06-03T18:00:00+01:00" 
```

i got

```
Traceback (most recent call last):
  File "v.in.sos.py", line 266, in <module>
    main()
  File "v.in.sos.py", line 152, in main
    password=options['password'])
  File "/usr/lib/python2.7/dist-packages/owslib/swe/observation/sos100.py", line 207, in get_observation
    raise ows.ExceptionReport(tr)
owslib.ows.ExceptionReport: 'Parameter "offering" sent with invalid value: LOCARNO,BELLINZONA'
```

**Comment by lucadelu** [comment]
I tested [the commit](https://github.com/pesekon2/GRASS-GIS-SOS-tools/commit/eed25c126b5151f2e04db080464a4f2a4fc7abc0) but it doesn't work properly because it overwrite the vector and at the end there is only a point. 
Probably it is better to work with pygrass vectors, because I think v.in.ogr is not the proper way to follow. You can look at these pages: [vectors](https://github.com/lucadelu/workshop-pygrass/blob/master/06_Vector_pygrass.ipynb), [vector geometries](https://github.com/lucadelu/workshop-pygrass/blob/master/05_Vector_geometries_pygrass.ipynb)

**Comment by pesekon2** [comment]
You're right, it gives only coordinates for one offering. And you're right also about that v.in.ogr isn't able to write new geometries without overwriting the old ones. (I was trying to do it for the whole forenoon)

I'm just working on a version with pygrass vectors. But how can I for example define the crs of inputting vectors? And are they importable normally to GRASS or just through some special tool? 
And also: How to specify for which points are the newly imported tables in attribute values writing?

**Comment by ninsbl** [comment]
You might have a look at:
https://trac.osgeo.org/grass/browser/grass-addons/grass7/vector/v.in.pygbif/v.in.pygbif.py
Where I had a similar use case of pygrass.
For points, direct reprojection should be OK. However, lines or polygons !might! requie densification of vertices (as could be done with v.proj).
If the SOS server returns a full geojson, maybe you can utilize the /vsicurl/ import [1] function of GDAL when using v.in.ogr, and import everything in one step?
1: http://erouault.blogspot.no/2012/05/new-gdal-virtual-file-system-to-read.html

**Comment by lucadelu** [comment]
I suggest you to check the input CRS using the Python OGR and OSR libraries. 
If you use pygrass vector it creates already a GRASS vector and you have no to import anything.

**Comment by lucadelu** [comment]
@ninsbl what could change using vsicurl?

**Comment by pesekon2** [comment]
Hi guys, thank you both very much for your help, I appreciate it. 

I have just pushed new commit working with pygrass instead of v.in.ogr. It seems to me that everything is working well and maybe better than with v.in.ogr (it isn't necessary to have millions of checks). But I will be very glad if you will also try it and have some recommendations. In case you won't find anything essential, I would like to merge the layers branch to the master. 

v.in.sos is now also able to work with larger data. Anyways, it's still falling with big enough data. 
For example `v.in.sos url=http://istsos.geodati.fmach.it/istsos/edenext? output=grida offering=GRIDA,GRIDC event_time='2012-03-14 18:28:01+01:00/2012-03-24 23:23:01+01:00' --overwrite` still works for me, but `v.in.sos url=http://istsos.geodati.fmach.it/istsos/edenext? output=grida offering=GRIDA,GRIDC event_time='2012-03-14 18:28:01+01:00/2012-03-24 23:23:01+01:00' --overwrite` doesn't. 
It raises many time warning `Coor file of vector map <grida@user1> is larger than it should be (18 bytes excess)`, I'm not really sure about how to solve it. I think this problem is in the user's RAM.

**Comment by ninsbl** [comment]
> @ninsbl what could change using vsicurl?

You are right, Luca, it would not change anything.

> For example v.in.sos url=http://istsos.geodati.fmach.it/istsos/edenext? output=grida offering=GRIDA,GRIDC event_time='2012-03-14 18:28:01+01:00/2012-03-24 23:23:01+01:00' --overwrite still works for me, but v.in.sos url=http://istsos.geodati.fmach.it/istsos/edenext? output=grida offering=GRIDA,GRIDC event_time='2012-03-14 18:28:01+01:00/2012-03-24 23:23:01+01:00' --overwrite doesn't.
It raises many time warning Coor file of vector map <grida@user1> is larger than it should be (18 bytes excess), I'm not really sure about how to solve it. I think this problem is in the user's RAM.

Just tested your examples (arent they identical BTW). For me they throw the following error message:
```
v.in.sos.py url=http://istsos.geodati.fmach.it/istsos/edenext? output=grida offering=GRIDA,GRIDC event_time='2012-03-14 18:28:01+01:00/2012-03-24 23:23:01+01:00' --overwrite
WARNING: Vector map <grida> already exists and will be overwritten
WARNING: Coor file of vector map <grida@u_stefan.blumentrath> is larger
         than it should be (18 bytes excess)
Building topology for vector map <grida@u_stefan.blumentrath>...
Registering primitives...
0 primitives registered
0 vertices registered
Building areas...
 100%
0 areas built
0 isles built
Attaching islands...
Attaching centroids...
Number of nodes: 0
Number of primitives: 0
Number of points: 0
Number of lines: 0
Number of boundaries: 0
Number of centroids: 0
Number of areas: 0
Number of isles: 0
Traceback (most recent call last):
  File "/data/src/GRASS-GIS-SOS-tools/v.in.sos/v.in.sos.py", line 335, in <module>
    main()
  File "/data/src/GRASS-GIS-SOS-tools/v.in.sos/v.in.sos.py", line 169, in main
    parsed_obs.update({property: xml2geojson(obs, property)})
TypeError: xml2geojson() takes exactly 1 argument (2 given)
```

I doubt it is a memory issue! In fact, I it seems to be an issue with empty maps in pygrass...

This :
```
from grass.pygrass.vector import VectorTopo
from grass.pygrass.vector.geometry import Point
new = VectorTopo('pygrass_test')
new.open('w')
new.close()
```

throws the "Coor file of vector map <grida@u_stefan.blumentrath> is larger than it should be (18 bytes excess)" error, while this:

```
from grass.pygrass.vector import VectorTopo
from grass.pygrass.vector.geometry import Point
new = VectorTopo('pygrass_test')
new.open('w')
point = Point(1, 2)
new.write(point)
new.close()
```

does not...

**Comment by pesekon2** [comment]
Thanks, you were right. I have solved the Coor warning. 

But there is still the problem with big data. Even without Coor I'm not able to use v.in.sos for `event_time='2012-03-15 18:28:01+01:00/2012-03-26 23:23:01+01:00'`

But I got completely different output. My output is:

```
Traceback (most recent call last):
  File "/usr/lib/grass73/scripts/v.in.sos", line 337, in <module>
    main()
  File "/usr/lib/grass73/scripts/v.in.sos", line 179, in main
    create_maps(parsed_obs, off, layerscount, new)
  File "/usr/lib/grass73/scripts/v.in.sos", line 281, in create_maps
    new.table.insert([insert], many=True)
  File "/usr/lib/grass73/etc/python/grass/pygrass/vector/table.py", line 1120, in insert
    return cur.executemany(self.columns.insert_str, values)
sqlite3.OperationalError: near ")": syntax error
```

I don't understand why is it looking like an syntax error since there isn't any for smaller time_event. 

The other thing I don't understand is why did you get error message `TypeError: xml2geojson() takes exactly 1 argument (2 given)` because [there](https://github.com/pesekon2/GRASS-GIS-SOS-tools/blob/layers/format_conversions/xml2geojson.py#L5) you can see it takes 2 arguments.

**Comment by ninsbl** [comment]
> The other thing I don't understand is why did you get error message TypeError: xml2geojson() takes exactly 1 argument (2 given) because there you can see it takes 2 arguments.

My bad. I tested the master branch, but I now see that the relevant changes are in the layers branch...

**Comment by lucadelu** [comment]
This is working for me
`v.in.sos.py url=http://istsos.geodati.fmach.it/istsos/edenext? output=grida offering=GRIDA,GRIDC event_time='2012-03-14 18:28:01+01:00/2012-03-24 23:23:01+01:00'`

Instead if I increase the event_time to `event_time='2012-03-15 18:28:01+01:00/2012-03-26 23:23:01+01:00'` I got the same error of @pesekon2 .

Running my first command works `v.in.sos.py url=http://istsos.org/istsos/demo? offering=LOCARNO,BELLINZONA observed_properties='urn:ogc:def:parameter:x-istsos:1.0:meteo:air:temperature' response_format='text/xml;subtype="om/1.0.0"' output=istsos_demo_2procs`

What I think is still invalid is related to the database, instead there are to many records.
If I run v.db.select on the output map I got something like this

```
v.db.select map=istsos_demo_2procs    
cat|t20140603T1550000200|t20140603T1430000200|name|t20140603T1450000200|t20140603T1510000200|t20140603T1420000200|t20140603T1440000200|t20140603T1530000200|t20140603T1500000200|t20140603T1520000200|t20140603T1540000200
1|20.600000||LOCARNO||||||||
2||20.200000|LOCARNO||||||||
3|||LOCARNO|20.500000|||||||
4|||LOCARNO||20.400000||||||
5|||LOCARNO|||20.100000|||||
6|||LOCARNO||||20.500000||||
7|||LOCARNO|||||19.100000|||
8|||LOCARNO||||||20.400000||
9|||LOCARNO|||||||19.600000|
10|||LOCARNO||||||||19.000000
```

Instead it should be something like

```
v.db.select map=istsos_demo_2procs    
cat|name|t20140603T1550000200|t20140603T1430000200|t20140603T1450000200|t20140603T1510000200|t20140603T1420000200|t20140603T1440000200|t20140603T1530000200|t20140603T1500000200|t20140603T1520000200|t20140603T1540000200
1|BELLINZONA|20.600000|20.200000||||||||
2|LOCARNO|||20.500000|20.400000|20.100000|20.500000|19.100000|20.400000|19.600000|19.000000
```
(I'm not sure if BELLINZONA is the first or second record)

This problem is related to the insert many command, you should insert first the name and later update the records adding the values....

We are getting close to finish this module :-)

**Comment by pesekon2** [comment]
Oh I see. 
Try it with new commit, it should work just like you suggested. 
The only difference between your suggestion and my implementation is in tables. It will give you another layer for BELLINZONA and another for LOCARNO. I still think that it's better to make another tables for another observed properties, but I can recode it into your suggested output. But try firstly this, where it's beneficial I think: 
`v.in.sos url=http://istsos.geodati.fmach.it/istsos/edenext? output=grida offering=GRIDA,GRIDC event_time='2012-03-15 18:28:01+01:00/2012-3-17 03:23:01+01:00' --overwrite`

But the SQLite problem with too many records still remains.

**Comment by ninsbl** [comment]
Maybe both ways to store the attribute data have their pros and cons. If you have one way working, maybe add the other one as a new option? Like the layout option (col, row, timerow) in [t.rast.what](https://grass.osgeo.org/grass73/manuals/t.rast.what.html)

That way users can chose the data layout they prefer? Just an idea...

**Comment by lucadelu** [comment]
@pesekon2 Your solution I think is really confusing with several data because it create to many records.

Maybe for t.vect.sos you should create a layer for each date with only a value,maybe this is a better solution than the actual...

**Comment by lucadelu** [comment]
Closing because this problem is solved....
